# Convolutional Neural Network

In [1]:
#Imorting dependencies

In [2]:
import numpy as np

In [3]:
# forming sample Convolutional Neural Network on AND gate

In [4]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y= np.array([[0,0,0,1]]).T

In [5]:
#using sigmod function
def sig(z):
    return 1/(1+np.exp(-z))

In [6]:
# finding derivative of sigmoid 
def dersig(z):
    return sig(z)*(1-sig(z))

In [7]:
# initialising with random number within range (-1,1)
weights = 2*np.random.random((2,1)) -1
bias = 2*np.random.random((1,1)) -1
weights,bias

(array([[ 0.56140195],
        [-0.49016215]]),
 array([[-0.87424748]]))

In [8]:
#using constant in gradient descent
alpha =20

In [9]:
#finding weights and bias using gradient descent 
for iter in range(100):    
    output0 = X
    
    opt = sig(np.dot(output0, weights) + bias)
    fir = opt-Y
    fir_inp = np.dot(output0, weights) + bias
    
    sec = dersig(fir_inp)
    
    ftwo = fir * sec
    
    changes = np.dot(output0.T,ftwo)
    bias_ch = np.sum(ftwo)
    weights = weights -alpha * changes
    bias = bias - alpha * bias_ch
output = sig(np.dot(X, weights) + bias)
weights,bias,output

(array([[7.2460756 ],
        [7.24510606]]),
 array([[-10.95598548]]),
 array([[1.74529314e-05],
        [2.38721883e-02],
        [2.38947911e-02],
        [9.71672787e-01]]))