# Convolutional Neural Network (With Hidden Layer)

In [1]:
#Imorting dependencies

In [2]:
import numpy as np

In [3]:
# forming sample Convolutional Neural Network on AND gate

In [4]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y= np.array([[0,1,1,0]]).T


In [5]:
#using sigmod function
def sig(z):
    return 1/(1+np.exp(-z))

In [6]:
# finding derivative of sigmoid 
def dersig(z):
    return sig(z)*(1-sig(z))

In [7]:
# initialising with random number within range (-1,1)

wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1

In [8]:
#using constant in gradient descent
alpha =0.1

In [9]:
#finding weights and bias using gradient descent 

for iter in range(100000):    
    input0 = X
    
    ip_hidden = np.dot(input0,wh)+bh
    op_hidden = sig(ip_hidden)
    
    ip_output = np.dot(op_hidden,wo)+bo
    op_output = sig(ip_output)
    
    der_e_out = op_output - Y
    der_out_hid = dersig(ip_output)
    two_out = der_e_out * der_out_hid
    
    der_o_hid = np.dot(two_out,wo.T)
    der_hid_inp = dersig(ip_hidden)
    two_hid = der_o_hid * der_hid_inp
    
    change_w_o = np.dot(op_hidden.T,two_out)
    change_b_o = np.sum(two_out , axis = 0 , keepdims = True)
    
    change_w_h = np.dot(input0.T,two_hid)
    change_b_h = np.sum(two_hid , axis = 0 , keepdims = True)
    wo = wo -alpha * change_w_o
    bo = bo -alpha * change_b_o
    wh = wh -alpha * change_w_h
    bh = bh -alpha * change_b_h
    


In [10]:

input0 = X
ip_hidden = np.dot(input0,wh)+bh
op_hidden = sig(ip_hidden)

ip_output = np.dot(op_hidden,wo)+bo
op_output = sig(ip_output)

print("Output\n",op_output,"\n\nWeights(Hidden)\n",wh,"\n\nBais(Hidden)\n",bh,"\n\nWeights(OutPut)\n",wo,"\n\nWeights(OutPut)\n",bo)

Output
 [[0.01190925]
 [0.98880746]
 [0.98637018]
 [0.01064327]] 

Weights(Hidden)
 [[-6.37249302 -6.0165632 ]
 [ 6.28971262  6.23559135]] 

Bais(Hidden)
 [[-3.40709376  3.01277759]] 

Weights(OutPut)
 [[10.23675775]
 [-9.96584722]] 

Weights(OutPut)
 [[4.75213008]]
